### ISSUE TITLE
Suggestion: Change navigation from numbers to letters

### ISSUE THREAD

**Issue by sabotrax** [TheCommsChannel/TC2-BBS-mesh#10]
Hi,
I'd like to suggest to change the navigational keys from numbers to letters.
So you wouldn't have to switch layers on the virtual keyboard on smart phones and tablets.

For example:
In the Mail Menu:
[r]Read [s][Send [e]Exit or [R]ead [S]end [E]xit instead of [0]Read ..

"r" would be a bit quicker to type than [?123] on an Android device and "0".

Greetings
Marcus

**Comment by upchui** [comment]
That could be nicely integrated so that it can be set in the config file as desired

**Comment by piranha32** [comment]
Just a thought: using digits instead of letters gives access to the main menu from any of the sub-menus

**Comment by TheCommsChannel** [comment]
This has been resolved in recent updates
