### ISSUE TITLE
T-deck compatibility

### ISSUE THREAD

**Issue by ronnietucker** [TheCommsChannel/TC2-BBS-mesh#26]
The BBS does work with the T-deck, but the menu is a bit wonky.

Strangely, when I read a message on the T-deck it flashed past quite quick, but it then asked me if I wanted to delete the read message. I haven't had that in the Meshtastic app. Nice touch though!

![IMG20240629123917](https://github.com/TheCommsChannel/TC2-BBS-mesh/assets/10391379/61c4f18c-6771-42e8-8e37-ee9e1037b6ec)

**Comment by TheCommsChannel** [comment]
Yeah, Meshtastic use on stand-alone devices won't be great until the update the UI. Hopefully soon!
