### ISSUE TITLE
Bulletin menu info and news wrong numbers

### ISSUE THREAD

**Issue by adam-cartwright** [TheCommsChannel/TC2-BBS-mesh#30]
When entering the Bulletin menu, you are presented with:

📰 BULLETIN MENU 📰
Which board would you like to enter?
[0]General  [1]Info  [2]News  [3]Urgent  [4]Exit

If you enter 1 you are taken to the News board, and 2 you are taken to the Info board. The assignments are reversed.

**Comment by adam-cartwright** [comment]
I just saw this is covered by and open PR. This issue can be closed.

**Comment by TheCommsChannel** [comment]
Thanks for the find! I'll go ahead and close this due to the PR.
