### ISSUE TITLE
Web client cannot work

### ISSUE THREAD

**Issue by cotteux** [TheCommsChannel/TC2-BBS-mesh#5]
If using the web client, you cannot use the BBS because web client don't let you send only one character.

Some minors thing, special code (utf8 character) not work on StandAlone Device.

**Comment by TheCommsChannel** [comment]
Ah, weird... I'll update how the menu works to fix this. Thanks for the heads up!

**Comment by cotteux** [comment]
Another thing to be useful, is the exit option in all menu to be always be the same character like 0

**Comment by cotteux** [comment]
i'm working to translate it in french

**Comment by justinxrenquist** [comment]
I can help translate to French, German, Dutch, Spanish..

**Comment by mzac** [comment]
![image](https://github.com/TheCommsChannel/TC2-BBS-mesh/assets/10270879/4d2ef34f-54d0-4db4-ae75-4999830d7a93)

**Comment by wishbone1138** [comment]
Bumping this, recommend all menu items move to at least two characters to support web client (or support both 1 and 2).  Maybe this is a smaller use case, but as this functionality expands I'm betting a lot of work to setup and populate a board will be done using the web client.  thanks!

**Comment by TheCommsChannel** [comment]
This has been fixed 
https://github.com/TheCommsChannel/TC2-BBS-mesh/commit/e9709fd781a5ddbbc6bb2331175948940bfc27cb
