### ISSUE TITLE
PR or Fork?

### ISSUE THREAD

**Issue by FractumSeraph** [TheCommsChannel/TC2-BBS-mesh#51]
Hello, I'm a big meshtastic enthusiast and I really like the software you've put together. I'm planning on adding a lot of features to this, and I'd of course want to make the code public.

I wanted to ask if you would prefer I forked the software and added the features there, or if I should submit them as pull requests or a different branch.
The features I plan on adding initially are door games adapted for mesh use, and some sort of watchdog for the serial connection since it seems to get stuck if the meshtastic device gets interrupted.

**Comment by TheCommsChannel** [comment]
Thanks! Appreciate anything you can add to the project!

I'm less interested in the door games, especially after having to trim down the menus to get them to consistently show. For things like that, I would say fork. I am interested in any fixes to make things work better, so feel free to send PRs for those.  I'm not aware of the serial connection issue if you can provide more details.
