### ISSUE TITLE
[IDEA] Replay to mail

### ISSUE THREAD

**Issue by Ztrby** [TheCommsChannel/TC2-BBS-mesh#57]
After reading a mail the reader are presented with 2 options, keep the mail och delete it. It would be nice to respond back with like "R"
And get the subject and shortname already done, so i only have to provide the text to send

**Comment by TheCommsChannel** [comment]
This was already implemented
https://github.com/TheCommsChannel/TC2-BBS-mesh/commit/15d836db2765e00e016d6859356b65d6d85efe7d

**Comment by Ztrby** [comment]
@TheCommsChannel , i used the CM command, maybe the code should be merged so CM and read in mailmenu use the same code

**Comment by TheCommsChannel** [comment]
I see. I'll have a look at that
