### ISSUE TITLE
menu behaviour change

### ISSUE THREAD

**Issue by gadd1** [TheCommsChannel/TC2-BBS-mesh#64]
Hi
In the initial version, when sending sub-menu letters it would answer, which is great as you can go directly to sub items like 'f' or 'w' to get a quick response. or jump directly to the Bulletin menu with 'b'. now you have to send 'x' to get it back to the main menu and start your way through the menu. which is time consuming when you know where you want to go.. 'h' is also not working which previously would prompt you with the menu

In any case great progress and development. hope the menu can continue to improve.

**Comment by TheCommsChannel** [comment]
Appreciate it.

I had to split up the menu handling because some of the sub menus have the same letter in other menus. [B]BS and [B]ulletins for example. I'll see what I can do for the non-duplicates when time allows.

H was essentially replaced with X
