### ISSUE TITLE
Not replying to outsiders

### ISSUE THREAD

**Issue by ronnietucker** [TheCommsChannel/TC2-BBS-mesh#67]
Hi!

I've finally got the BBS running smooth on a _Pi 4B_ with a _Heltec_ connected to it by USB (ttyUSB0).

I can send commands and get replies no problem, but others from elsewhere have been sending an initial message (to get the menu) but not getting a reply.

Any idea what might cause this? I can see them sending the initial message in my terminal.

**Thanks, and keep up the great work!**
_Ronnie_

**Comment by TheCommsChannel** [comment]
Glad you got it up and running!

If you're able to get replies and they can't, there's no issue with the BBS itself. They're probably out of range (and can probably get intermittently get replies if they continue trying) BSS is ideally meant to be deployed at good locations.
