### ISSUE TITLE
Can't See Messages to Node

### ISSUE THREAD

**Issue by SpeedGP** [TheCommsChannel/TC2-BBS-mesh#74]
When a message comes to the node now, I'm not able to see what they send. Is it possible if they type anything other than a single character, to at least show the message to the app?

Sorry if  that doesn't make sense. I'm just curious if someone is direct messaging me, but the BBS picks up and there is no way to know what they are asking me - if that makes sense.

**Comment by TheCommsChannel** [comment]
Unfortunately, it's not possible to have the node running the BBS and the Android/iOS client at the same time.
